# Generated by Django 5.0 on 2023-12-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона с кодом страны')),
            ],
        ),
    ]
