# Generated by Django 5.0 on 2023-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_pass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Туриста', 'verbose_name_plural': 'Туристы'},
        ),
    ]
