# Generated by Django 5.0 on 2023-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_pass', '0003_levels_pass_passimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passimages',
            name='image_id',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
