# Generated by Django 5.0 on 2023-12-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_pass', '0004_alter_passimages_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passimages',
            name='image_id',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
