# Generated by Django 5.0 on 2023-12-25 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_pass', '0006_alter_passimages_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='pass_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='add_pass.pass'),
            preserve_default=False,
        ),
    ]
