# Generated by Django 5.0 on 2023-12-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_pass', '0007_coords_pass_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coords',
            name='pass_id',
        ),
        migrations.AddField(
            model_name='pass',
            name='coords',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='add_pass.coords'),
            preserve_default=False,
        ),
    ]
